name: Upload Sentry Source Maps from Supabase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Precheck secrets
        run: |
          test -n "$SUPABASE_SERVICE_ROLE_KEY" || (echo "❌ Missing SUPABASE_SERVICE_ROLE_KEY" && exit 1)
          test -n "$VITE_SUPABASE_URL" || (echo "❌ Missing VITE_SUPABASE_URL" && exit 1)
          test -n "$VITE_SUPABASE_ANON_KEY" || (echo "❌ Missing VITE_SUPABASE_ANON_KEY" && exit 1)

      - name: Fetch Sentry token from Supabase
        id: get_token
        run: |
          curl -s $VITE_SUPABASE_URL/functions/v1/get-sentry-token \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            | jq -r '.token' > token.txt
          echo "SENTRY_AUTH_TOKEN=$(cat token.txt)" >> $GITHUB_ENV

      - name: Build app (Sentry sourcemaps auto-upload via Vite plugin)
        run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
